---
- name: 'Create directory for container data'
  file:
    path: "{{ minecraft_server_data_dir }}"
    state: "directory"
    recurse: true
    mode: 0744

- name: 'Send environment file for Minecraft docker'
  template:
    src: "minecraft_server.yml.j2"
    dest: "{{ minecraft_server_data_dir }}/minecraft_server.yml"
    mode: 0644

- name: 'Move mods to the server'
  synchronize:
    delete: true
    recursive: true
    src: "{{ minecraft_server_mods_dir_on_host }}"
    dest: "{{ minecraft_server_data_dir }}"
    copy_links: false
  when: minecraft_server_mods_dir_on_host

- name: 'Deploy Minecraft Server'
  community.docker.docker_compose:
    project_src: "{{ minecraft_server_data_dir }}"
    state: present
    files:
      - "minecraft_server.yml"
